import { Asset, Category, User, IncidentReport } from './types';

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat-vehicules', nom: 'Véhicules & Flotte', code: 'VEHICULE', icone: 'Car' },
  { id: 'cat-machines', nom: 'Machines & Équipements', code: 'MACHINE', icone: 'Cpu' },
  { id: 'cat-informatique', nom: 'Matériel Informatique', code: 'INFORMATIQUE', icone: 'Laptop' },
  { id: 'cat-mobilier', nom: 'Mobilier de Bureau', code: 'MOBILIER', icone: 'Armchair' },
  { id: 'cat-autre', nom: 'Autres Immobilisations', code: 'AUTRE', icone: 'Box' },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'user-admin-1',
    nom: 'Alexandre Dupont',
    email: 'admin@meteor-pro.dz',
    passwordHash: '$2b$10$jHWSUzsgJ5ICQbOtKsl6OebKMC06t/BrbeVoOoyWA0HDnptIyz5Zm',
    role: 'ADMIN',
    departement: 'Direction des Opérations',
    createdAt: '2024-01-01T08:00:00.000Z',
    updatedAt: '2024-01-01T08:00:00.000Z',
  },
  {
    id: 'user-gest-1',
    nom: 'Sophie Martin',
    email: 'gestionnaire@meteor-pro.dz',
    passwordHash: '$2b$10$cp9EILCXi25sSPpijmdvbOOa53Oi6PO8LAelesYf7/p8J2ur8VeT2',
    role: 'GESTIONNAIRE',
    departement: 'Services Généraux & Logistique',
    createdAt: '2024-01-15T09:30:00.000Z',
    updatedAt: '2024-01-15T09:30:00.000Z',
  },
  {
    id: 'user-emp-1',
    nom: 'Thomas Leroy',
    email: 'employe@meteor-pro.dz',
    passwordHash: '$2b$10$hCACx1J/naZW3.EhGzg/p.R.xdqvzgqR1En9H0ajxdzvCaWK4d0XW',
    role: 'EMPLOYE',
    departement: 'Maintenance & Terrain',
    createdAt: '2024-02-01T10:00:00.000Z',
    updatedAt: '2024-02-01T10:00:00.000Z',
  },
];

// Calculation helper for realistic dates
const now = new Date();
const addDays = (d: Date, days: number) => {
  const res = new Date(d);
  res.setDate(res.getDate() + days);
  return res.toISOString();
};
const subMonths = (d: Date, months: number) => {
  const res = new Date(d);
  res.setMonth(res.getMonth() - months);
  return res.toISOString();
};

export const INITIAL_ASSETS: Asset[] = [
  {
    id: 'ast-v-001',
    nom: 'Renault Master III dCi 150 Grand Volume',
    numeroInventaire: 'IMM-2023-V01',
    description: 'Fourgon utilitaire atelier équipé, transport outillage et matériel lourd pour équipes d’intervention.',
    dateAcquisition: '2023-03-15T00:00:00.000Z',
    valeurAcquisition: 5850000,
    valeurActuelle: 4100000,
    fournisseur: 'Renault Pro+ Algérie',
    numeroFacture: 'FAC-REN-2023-9082',
    site: 'Site Usine Nord',
    batiment: 'Atelier Central',
    service: 'Maintenance Industrielle',
    statut: 'EN_SERVICE',
    photos: [
      'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80',
    ],
    documents: ['Certificat d’immatriculation.pdf', 'Contrat_Assurance_Flotte_2024.pdf'],
    createdAt: '2023-03-15T10:00:00.000Z',
    updatedAt: '2024-08-10T14:30:00.000Z',
    categoryId: 'cat-vehicules',
    responsableId: 'user-gest-1',
    vehicle: {
      id: 'veh-001',
      assetId: 'ast-v-001',
      immatriculation: '16-12345-123',
      marque: 'Renault',
      modele: 'Master III 2.3 dCi',
      annee: 2023,
      typeCarburant: 'Diesel',
      kilometrage: 64250,
      dateDernierControle: subMonths(now, 18),
      dateProchainControle: addDays(now, 14), // URGENCE: contrôle technique dans 14 jours !
      dateAssurance: subMonths(now, 11),
      dateEcheanceAssurance: addDays(now, 22), // URGENCE: assurance expire dans 22 jours !
      conducteurHabituelId: 'user-emp-1',
    },
    maintenanceLogs: [
      {
        id: 'mnt-001',
        assetId: 'ast-v-001',
        date: subMonths(now, 2),
        typeIntervention: 'Révision 60 000 km + Changement plaquettes',
        cout: 65000,
        prestataire: 'Garage Central',
        notes: 'Vidange, filtres huile/air/gasoil, plaquettes avant changées. R.A.S sur suspension.',
        createdAt: subMonths(now, 2),
      },
      {
        id: 'mnt-002',
        assetId: 'ast-v-001',
        date: subMonths(now, 7),
        typeIntervention: 'Remplacement pneumatiques avant',
        cout: 42000,
        prestataire: 'Pneumatiques Service',
        notes: 'Pneus Michelin montés et équilibrés.',
        createdAt: subMonths(now, 7),
      },
    ],
    incidentReports: [],
  },
  {
    id: 'ast-v-002',
    nom: 'Peugeot 208 Électrique e-208 GT',
    numeroInventaire: 'IMM-2023-V02',
    description: 'Véhicule de liaison urbain zéro-émission affecté aux déplacements des coordinateurs de site.',
    dateAcquisition: '2023-06-20T00:00:00.000Z',
    valeurAcquisition: 4600000,
    valeurActuelle: 3680000,
    fournisseur: 'Peugeot Métropole',
    numeroFacture: 'PEUG-2023-047',
    site: 'Siège Social',
    batiment: 'Bâtiment Tertiaire A',
    service: 'Direction Générale',
    statut: 'EN_SERVICE',
    photos: [
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80',
    ],
    documents: ['Carte_Grise_e208.pdf'],
    createdAt: '2023-06-20T11:00:00.000Z',
    updatedAt: '2024-07-01T09:00:00.000Z',
    categoryId: 'cat-vehicules',
    responsableId: 'user-admin-1',
    vehicle: {
      id: 'veh-002',
      assetId: 'ast-v-002',
      immatriculation: '16-98765-123',
      marque: 'Peugeot',
      modele: 'e-208 GT 136ch',
      annee: 2023,
      typeCarburant: 'Électrique',
      kilometrage: 28400,
      dateDernierControle: subMonths(now, 12),
      dateProchainControle: addDays(now, 120),
      dateAssurance: subMonths(now, 8),
      dateEcheanceAssurance: addDays(now, 115),
      conducteurHabituelId: 'user-gest-1',
    },
    maintenanceLogs: [
      {
        id: 'mnt-003',
        assetId: 'ast-v-002',
        date: subMonths(now, 3),
        typeIntervention: 'Contrôle système haute-tension & mise à jour logiciel',
        cout: 28000,
        prestataire: 'Concession Peugeot',
        notes: 'Bilan de santé batterie (SOH 99%). Remplacement filtre habitacle.',
        createdAt: subMonths(now, 3),
      },
    ],
    incidentReports: [],
  },
  {
    id: 'ast-m-001',
    nom: 'Chariot Élévateur Électrique Fenwick E16C',
    numeroInventaire: 'IMM-2022-M03',
    description: 'Chariot frontal électrique 3 roues, capacité 1.6T, mât triplex 4650 mm pour manutention palettes.',
    dateAcquisition: '2022-09-10T00:00:00.000Z',
    valeurAcquisition: 3800000,
    valeurActuelle: 2280000,
    fournisseur: 'Fenwick-Linde',
    numeroFacture: 'FEN-2022-991',
    site: 'Entrepôt Logistique',
    batiment: 'Quai Réception Hangar 2',
    service: 'Stockage & Expéditions',
    statut: 'EN_MAINTENANCE',
    photos: [
      'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=800&q=80',
    ],
    documents: ['Manuel_Utilisateur_Fenwick.pdf', 'Certificat_CE.pdf'],
    createdAt: '2022-09-10T08:30:00.000Z',
    updatedAt: '2024-09-01T15:00:00.000Z',
    categoryId: 'cat-machines',
    responsableId: 'user-emp-1',
    maintenanceLogs: [
      {
        id: 'mnt-004',
        assetId: 'ast-m-001',
        date: subMonths(now, 1),
        typeIntervention: 'Diagnostic vérin hydraulique',
        cout: 85000,
        prestataire: 'Fenwick Service',
        notes: 'Légère fuite d’huile sur joint de vérin de levée. Pièce commandée, en attente montage.',
        createdAt: subMonths(now, 1),
      },
    ],
    incidentReports: [
      {
        id: 'inc-001',
        assetId: 'ast-m-001',
        date: subMonths(now, 1),
        titre: 'Fuite hydraulique constatée au démarrage',
        description: 'Taches d’huile au sol sous le mât au poste de charge. Machine consignée temporairement.',
        statut: 'EN_COURS',
        signalePar: 'Thomas Leroy',
        createdAt: subMonths(now, 1),
      },
    ],
  },
  {
    id: 'ast-i-001',
    nom: 'Serveur Rack Dell PowerEdge R750xs 2U',
    numeroInventaire: 'IMM-2023-I12',
    description: 'Serveur d’infrastructure hébergeant la virtualisation locale et les sauvegardes redondantes.',
    dateAcquisition: '2023-01-18T00:00:00.000Z',
    valeurAcquisition: 1950000,
    valeurActuelle: 1365000,
    fournisseur: 'Dell Technologies',
    numeroFacture: 'DELL-INV-88219',
    site: 'Siège Social',
    batiment: 'Salle Serveurs Sécurisée',
    service: 'DSI / Systèmes & Réseaux',
    statut: 'EN_SERVICE',
    photos: [
      'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=800&q=80',
    ],
    documents: ['Garantie_ProSupport_Dell_5Ans.pdf'],
    createdAt: '2023-01-18T14:00:00.000Z',
    updatedAt: '2024-05-12T10:00:00.000Z',
    categoryId: 'cat-informatique',
    responsableId: 'user-admin-1',
    maintenanceLogs: [
      {
        id: 'mnt-005',
        assetId: 'ast-i-001',
        date: subMonths(now, 5),
        typeIntervention: 'Mise à jour firmware iDRAC et BIOS',
        cout: 0,
        prestataire: 'Interne DSI',
        notes: 'Patchs de sécurité appliqués avec succès hors heures de production.',
        createdAt: subMonths(now, 5),
      },
    ],
    incidentReports: [],
  },
  {
    id: 'ast-i-002',
    nom: 'Lot 5x MacBook Pro 16" M3 Pro 36Go',
    numeroInventaire: 'IMM-2024-I04',
    description: 'Postes de travail haute performance pour équipe de conception technique et développement.',
    dateAcquisition: '2024-02-10T00:00:00.000Z',
    valeurAcquisition: 2450000,
    valeurActuelle: 2080000,
    fournisseur: 'Apple Store Entreprise',
    numeroFacture: 'APL-DZ-2024-119',
    site: 'Siège Social',
    batiment: 'Open Space Ingénierie',
    service: 'Bureau d’Études',
    statut: 'EN_SERVICE',
    photos: [
      'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80',
    ],
    documents: ['Facture_Apple.pdf', 'AppleCare_Certificats.pdf'],
    createdAt: '2024-02-10T09:00:00.000Z',
    updatedAt: '2024-02-10T09:00:00.000Z',
    categoryId: 'cat-informatique',
    responsableId: 'user-gest-1',
    maintenanceLogs: [],
    incidentReports: [],
  },
  {
    id: 'ast-b-001',
    nom: 'Ensemble Mobilier Salle du Conseil (Table modulaire 16p + Sièges cuir)',
    numeroInventaire: 'IMM-2021-B08',
    description: 'Grande table de conférence électrifiée avec connectique HDMI/USB-C intégrée et 16 fauteuils ergonomiques.',
    dateAcquisition: '2021-11-05T00:00:00.000Z',
    valeurAcquisition: 1200000,
    valeurActuelle: 480000,
    fournisseur: 'Mobilier Professionnel',
    numeroFacture: 'STC-2021-7721',
    site: 'Siège Social',
    batiment: 'Bâtiment Direction - Étage 3',
    service: 'Services Généraux',
    statut: 'EN_SERVICE',
    photos: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80',
    ],
    documents: ['Plan_Agencement_Conseil.pdf'],
    createdAt: '2021-11-05T16:00:00.000Z',
    updatedAt: '2024-01-10T11:00:00.000Z',
    categoryId: 'cat-mobilier',
    responsableId: 'user-gest-1',
    maintenanceLogs: [],
    incidentReports: [],
  },
];
